### ISSUE TITLE
Failure to Compile CPP Examples

### ISSUE THREAD

**Issue by BilalAhmad-Bhatti** [GMLC-TDC/HELICS-Examples#74]
I am trying to run the following cpp example from HELICS-Examples repo:
https://github.com/GMLC-TDC/HELICS-Examples/blob/main/cpp/valueFederate1/valueFed.cpp
using instructions:
https://github.com/GMLC-TDC/HELICS-Examples

I have downloaded the HELICS pre-compiled library for cpp (v2.8). I have also set the HELICS_DIR environment variable to the required path:
![image](https://user-images.githubusercontent.com/77303091/182255645-237207ca-8b52-4d74-91a9-d92017df410c.png)

However, I keep getting the following error in cmake:
![image](https://user-images.githubusercontent.com/77303091/182255588-4084e402-90f6-4dc1-9fcb-26d931bb47a2.png)

**Comment by nightlark** [comment]
HELICS v2 is no longer supported -- though it does look like the C/C++/C++98 examples really need an updating to support HELICS 3 as well. A version of the comboFed example that is used as part of the HELICS CI builds can be found in https://github.com/GMLC-TDC/HELICS/tree/main/examples

**Comment by trevorhardy** [comment]
I talked with @BilalAhmad-Bhatti about this and the current CMAKE files do not work for a HELICS v3 and need to be updated by somebody who knows CMAKE.

**Comment by BilalAhmad-Bhatti** [comment]
@nightlark I tried running combo federate example in the repo you mentioned. I get following:
![image](https://user-images.githubusercontent.com/77303091/182474967-d46207e9-3dd6-4888-9329-2ac5d57920e2.png)

**Comment by nightlark** [comment]
It isn’t set up to build as a standalone CMake project, only as a
subproject of the top-level HELICS build.

**Comment by BilalAhmad-Bhatti** [comment]
Is there a guide on running this?

**Comment by nightlark** [comment]
As it is mainly for one of the CI tests, there isn't any guide to using it. Building it is just a matter of setting one of the CMake options to ON when building HELICS https://docs.helics.org/en/latest/user-guide/installation/helics_cmake_options.html?highlight=HELICS_BUILD_EXAMPLES

**Comment by BilalAhmad-Bhatti** [comment]
I see. It seems like the standalone cmake version (which I suspect is in HELICS-examples repo) would be more useful for me since i am aiming for a standalone application. 
Any idea on how long it would take for that repo to be updated?

**Comment by nightlark** [comment]
I'm not sure. One thing I just noticed now though is that you mentioned downloading the precompiled HELICS library for cpp -- we don't have any downloads that include a precompiled c++ shared library, since compatibility is hard to guarantee with c++ and can very even between minor/patch releases of the same compiler or c++ standard library. The pre-compiled libraries included in releases are the c library, and the c++98 compatible headers that wrap the c library functions.

To get an install with a valid HELCS::helics-apps-cpp target you need to build HELICS from source with the `HELICS_BUILD_CXX_SHARED_LIB` and `HELICS_BUILD_APP_LIBRARY` options enabled.
https://docs.helics.org/en/latest/user-guide/installation/helics_cmake_options.html?highlight=HELICS_BUILD_CXX_SHARED_LIB
https://docs.helics.org/en/latest/user-guide/installation/helics_cmake_options.html?highlight=HELICS_BUILD_APP_LIBRARY

**Comment by BilalAhmad-Bhatti** [comment]
@nightlark Thanks for the clarification. If I understood correctly, for running examples in https://github.com/GMLC-TDC/HELICS/tree/main/examples , I need to build HELICS from source. Can you share the latest guide for building HELICS?

**Comment by trevorhardy** [comment]
Here you go, @BilalAhmad-Bhatti: https://docs.helics.org/en/latest/user-guide/installation/build_from_source.html

**Comment by BilalAhmad-Bhatti** [comment]
Thanks Trevor
